// Generated by Framer (88cdfe9)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "wge8mc", mediaQuery: "(min-width: 1440px)"}, {hash: "pgye67", mediaQuery: "(min-width: 1200px) and (max-width: 1439.98px)"}, {hash: "56vyku", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "1jybmvd", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {Sv3kanvJx: "top"}, robots: "max-image-preview:large", serializationId: "framer-cnQhs", title: siteMetadata(params, activeLocale).title || "About", viewport: "width=device-width"}
}

export const metadataVersion = 1