// Generated by Framer (83b8097)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-Az7O9AQug", breakpoints: [{hash: "je6pdg"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-DpHy7", title: siteMetadata(params, activeLocale).title || "Landing Page", viewport: "width=1440"}
}

export const metadataVersion = 1