// Generated by Framer (2fef4c5)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "14wgonl", mediaQuery: "(min-width: 1440px)"}, {hash: "1y79412", mediaQuery: "(min-width: 1200px) and (max-width: 1439px)"}, {hash: "ls79xa", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "gjrouq", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {anCeed4O5: "top"}, framerSearch: {index: false}, robots: "noindex", serializationId: "framer-Ni7H1", title: siteMetadata(params, activeLocale).title || "404", viewport: "width=device-width"}
}

export const metadataVersion = 1