// Generated by Framer (5bbf1f3)

import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const aj5Onj2wB = params?.aj5Onj2wB
return {bodyClassName: "framer-body-rQGU9cDX3", breakpoints: [{hash: "1i2iy1w"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-UkJdX", title: `${aj5Onj2wB !== undefined ? toString(aj5Onj2wB) : "{{aj5Onj2wB}}"} - Viper - Portfolio`, viewport: "width=1440"}
}

export const metadataVersion = 1