// Generated by Framer (74099f6)
import {
    jsx as _jsx,
    jsxs as _jsxs,
    Fragment as _Fragment
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    Floating,
    getFonts,
    SmartComponentScopedContainer,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useOverlayState,
    useVariantState,
    withCSS,
    withFX
} from "framer";
import {
    AnimatePresence,
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import Ticker from "https://framerusercontent.com/modules/B2xAlJLcN0gOnt11mSPw/LHz3bw67SqHRmnCKTlE6/Ticker.js";
import Slideshow from "https://framerusercontent.com/modules/zvkTOpMSuRzRhLzZZIwG/gveXKR6bwXNSCLv12kr3/SlideShow.js";
import ClientCardXL from "https://framerusercontent.com/modules/5ccGyzSF54nSDcNUeg3t/BjknMqDTM52jJk8ghgVE/AUdIPWa8L.js";
const ClientCardXLFonts = getFonts(ClientCardXL);
const TickerFonts = getFonts(Ticker);
const SlideshowFonts = getFonts(Slideshow);
const MotionDivWithFX = withFX(motion.div);
const cycleOrder = ["YmEHXmhgM", "BbZ4PDuqX"];
const serializationHash = "framer-8OLiA";
const variantClassNames = {
    BbZ4PDuqX: "framer-v-1qckcgx",
    YmEHXmhgM: "framer-v-1gghnu2"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const addImageAlt = (image, alt) => {
    if (!image || typeof image !== "object") {
        return;
    }
    return { ...image,
        alt
    };
};
const animation = {
    opacity: 0,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    transition: transition1,
    x: 0,
    y: 0
};
const animation1 = {
    opacity: 1,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    transition: transition1,
    x: 0,
    y: 0
};
const animation2 = {
    opacity: 0,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: 0
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Overlay = ({
    children,
    blockDocumentScrolling,
    enabled = true
}) => {
    const [visible, setVisible] = useOverlayState({
        blockDocumentScrolling
    });
    return children({
        hide: () => setVisible(false),
        show: () => setVisible(true),
        toggle: () => setVisible(!visible),
        visible: enabled && visible
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Slider: "BbZ4PDuqX",
    Ticker: "YmEHXmhgM"
};
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "YmEHXmhgM"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "YmEHXmhgM",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const onMouseEnterupml6a = ({
        overlay,
        loadMore
    }) => activeVariantCallback(async (...args) => {
        setGestureState({
            isHovered: true
        });
        overlay.show();
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed = () => {
        if (baseVariant === "BbZ4PDuqX") return false;
        return true;
    };
    const isDisplayed1 = () => {
        if (baseVariant === "BbZ4PDuqX") return true;
        return false;
    };
    const ref1 = React.useRef(null);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Overlay, {
                blockDocumentScrolling: false,
                children: overlay => /*#__PURE__*/ _jsx(_Fragment, {
                    children: /*#__PURE__*/ _jsx(Transition, {
                        value: transition1,
                        children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                            ...gestureHandlers,
                            className: cx(scopingClassNames, "framer-1gghnu2", className, classNames),
                            "data-framer-name": "Ticker",
                            "data-highlight": true,
                            id: `${layoutId}-1gghnu2`,
                            layoutDependency: layoutDependency,
                            layoutId: "YmEHXmhgM",
                            onMouseEnter: onMouseEnterupml6a({
                                overlay
                            }),
                            ref: refBinding,
                            style: { ...style
                            },
                            ...addPropertyOverrides({
                                BbZ4PDuqX: {
                                    "data-framer-name": "Slider"
                                }
                            }, baseVariant, gestureVariant),
                            children: [isDisplayed() && /*#__PURE__*/ _jsx(motion.div, {
                                className: "framer-7optrw",
                                "data-framer-name": "Line",
                                layoutDependency: layoutDependency,
                                layoutId: "LG3ewVWnA",
                                style: {
                                    backgroundColor: "var(--token-bf3b78f1-7c89-4ecd-bba4-77c1a4c7b347, rgb(234, 234, 234))",
                                    opacity: .65
                                }
                            }), isDisplayed() && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                    className: "framer-129g3z6-container",
                                    isAuthoredByUser: true,
                                    isModuleExternal: true,
                                    layoutDependency: layoutDependency,
                                    layoutId: "N5nguNu8U-container",
                                    nodeId: "N5nguNu8U",
                                    rendersWithMotion: true,
                                    scopeId: "BmyWZK_C9",
                                    children: /*#__PURE__*/ _jsx(Ticker, {
                                        alignment: "center",
                                        direction: "left",
                                        fadeOptions: {
                                            fadeAlpha: 0,
                                            fadeContent: false,
                                            fadeInset: 0,
                                            fadeWidth: 25,
                                            overflow: false
                                        },
                                        gap: 0,
                                        height: "100%",
                                        hoverFactor: .6,
                                        id: "N5nguNu8U",
                                        layoutId: "N5nguNu8U",
                                        padding: 0,
                                        paddingBottom: 0,
                                        paddingLeft: 0,
                                        paddingPerSide: false,
                                        paddingRight: 0,
                                        paddingTop: 0,
                                        sizingOptions: {
                                            heightType: true,
                                            widthType: true
                                        },
                                        slots: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                            height: 180,
                                            width: "268px",
                                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                                className: "framer-jn1a0j-container",
                                                inComponentSlot: true,
                                                layoutDependency: layoutDependency,
                                                layoutId: "efiHBbLQA-Uyin_DcTz-0-container",
                                                nodeId: "Uyin_DcTz",
                                                rendersWithMotion: true,
                                                scopeId: "BmyWZK_C9",
                                                children: /*#__PURE__*/ _jsx(ClientCardXL, {
                                                    height: "100%",
                                                    id: "Uyin_DcTz",
                                                    layoutId: "efiHBbLQA-Uyin_DcTz-0",
                                                    Ln8d5mN1s: addImageAlt({
                                                        pixelHeight: 2560,
                                                        pixelWidth: 2560,
                                                        src: "https://framerusercontent.com/images/nvwMzGj6it9ES02wDvpqv67cBa0.jpg?width=2560&height=2560",
                                                        srcSet: "https://framerusercontent.com/images/nvwMzGj6it9ES02wDvpqv67cBa0.jpg?scale-down-to=512&width=2560&height=2560 512w,https://framerusercontent.com/images/nvwMzGj6it9ES02wDvpqv67cBa0.jpg?scale-down-to=1024&width=2560&height=2560 1024w,https://framerusercontent.com/images/nvwMzGj6it9ES02wDvpqv67cBa0.jpg?scale-down-to=2048&width=2560&height=2560 2048w,https://framerusercontent.com/images/nvwMzGj6it9ES02wDvpqv67cBa0.jpg?width=2560&height=2560 2560w"
                                                    }, ""),
                                                    style: {
                                                        height: "100%",
                                                        width: "100%"
                                                    },
                                                    variant: "fg2Qm7JpU",
                                                    width: "100%"
                                                })
                                            })
                                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                            height: 180,
                                            width: "268px",
                                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                                className: "framer-rrowkn-container",
                                                inComponentSlot: true,
                                                layoutDependency: layoutDependency,
                                                layoutId: "C4qTlRtN0-ZZATUfibb-1-container",
                                                nodeId: "ZZATUfibb",
                                                rendersWithMotion: true,
                                                scopeId: "BmyWZK_C9",
                                                children: /*#__PURE__*/ _jsx(ClientCardXL, {
                                                    height: "100%",
                                                    id: "ZZATUfibb",
                                                    layoutId: "C4qTlRtN0-ZZATUfibb-1",
                                                    Ln8d5mN1s: addImageAlt({
                                                        pixelHeight: 2560,
                                                        pixelWidth: 2560,
                                                        src: "https://framerusercontent.com/images/2HNBj8EpPhWYN2mTxm1qVqTjEY.jpg?width=2560&height=2560",
                                                        srcSet: "https://framerusercontent.com/images/2HNBj8EpPhWYN2mTxm1qVqTjEY.jpg?scale-down-to=512&width=2560&height=2560 512w,https://framerusercontent.com/images/2HNBj8EpPhWYN2mTxm1qVqTjEY.jpg?scale-down-to=1024&width=2560&height=2560 1024w,https://framerusercontent.com/images/2HNBj8EpPhWYN2mTxm1qVqTjEY.jpg?scale-down-to=2048&width=2560&height=2560 2048w,https://framerusercontent.com/images/2HNBj8EpPhWYN2mTxm1qVqTjEY.jpg?width=2560&height=2560 2560w"
                                                    }, ""),
                                                    style: {
                                                        height: "100%",
                                                        width: "100%"
                                                    },
                                                    variant: "fg2Qm7JpU",
                                                    width: "100%"
                                                })
                                            })
                                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                            height: 180,
                                            width: "268px",
                                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                                className: "framer-x106js-container",
                                                inComponentSlot: true,
                                                layoutDependency: layoutDependency,
                                                layoutId: "V9wukmpzg-dA0uXeoXY-2-container",
                                                nodeId: "dA0uXeoXY",
                                                rendersWithMotion: true,
                                                scopeId: "BmyWZK_C9",
                                                children: /*#__PURE__*/ _jsx(ClientCardXL, {
                                                    height: "100%",
                                                    id: "dA0uXeoXY",
                                                    layoutId: "V9wukmpzg-dA0uXeoXY-2",
                                                    Ln8d5mN1s: addImageAlt({
                                                        pixelHeight: 2560,
                                                        pixelWidth: 2560,
                                                        src: "https://framerusercontent.com/images/eg04bFcNkzl2gTkfiGuozksUGY.jpg?width=2560&height=2560",
                                                        srcSet: "https://framerusercontent.com/images/eg04bFcNkzl2gTkfiGuozksUGY.jpg?scale-down-to=512&width=2560&height=2560 512w,https://framerusercontent.com/images/eg04bFcNkzl2gTkfiGuozksUGY.jpg?scale-down-to=1024&width=2560&height=2560 1024w,https://framerusercontent.com/images/eg04bFcNkzl2gTkfiGuozksUGY.jpg?scale-down-to=2048&width=2560&height=2560 2048w,https://framerusercontent.com/images/eg04bFcNkzl2gTkfiGuozksUGY.jpg?width=2560&height=2560 2560w"
                                                    }, ""),
                                                    style: {
                                                        height: "100%",
                                                        width: "100%"
                                                    },
                                                    variant: "fg2Qm7JpU",
                                                    width: "100%"
                                                })
                                            })
                                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                            height: 180,
                                            width: "268px",
                                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                                className: "framer-rrowkn-container",
                                                inComponentSlot: true,
                                                layoutDependency: layoutDependency,
                                                layoutId: "cznYR1Hg7-ZZATUfibb-3-container",
                                                nodeId: "ZZATUfibb",
                                                rendersWithMotion: true,
                                                scopeId: "BmyWZK_C9",
                                                children: /*#__PURE__*/ _jsx(ClientCardXL, {
                                                    height: "100%",
                                                    id: "ZZATUfibb",
                                                    layoutId: "cznYR1Hg7-ZZATUfibb-3",
                                                    Ln8d5mN1s: addImageAlt({
                                                        pixelHeight: 2560,
                                                        pixelWidth: 2560,
                                                        src: "https://framerusercontent.com/images/2HNBj8EpPhWYN2mTxm1qVqTjEY.jpg?width=2560&height=2560",
                                                        srcSet: "https://framerusercontent.com/images/2HNBj8EpPhWYN2mTxm1qVqTjEY.jpg?scale-down-to=512&width=2560&height=2560 512w,https://framerusercontent.com/images/2HNBj8EpPhWYN2mTxm1qVqTjEY.jpg?scale-down-to=1024&width=2560&height=2560 1024w,https://framerusercontent.com/images/2HNBj8EpPhWYN2mTxm1qVqTjEY.jpg?scale-down-to=2048&width=2560&height=2560 2048w,https://framerusercontent.com/images/2HNBj8EpPhWYN2mTxm1qVqTjEY.jpg?width=2560&height=2560 2560w"
                                                    }, ""),
                                                    style: {
                                                        height: "100%",
                                                        width: "100%"
                                                    },
                                                    variant: "fg2Qm7JpU",
                                                    width: "100%"
                                                })
                                            })
                                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                            height: 180,
                                            width: "268px",
                                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                                className: "framer-66sskk-container",
                                                inComponentSlot: true,
                                                layoutDependency: layoutDependency,
                                                layoutId: "QeB8vrZl3-k0qgt1bmX-4-container",
                                                nodeId: "k0qgt1bmX",
                                                rendersWithMotion: true,
                                                scopeId: "BmyWZK_C9",
                                                children: /*#__PURE__*/ _jsx(ClientCardXL, {
                                                    height: "100%",
                                                    id: "k0qgt1bmX",
                                                    layoutId: "QeB8vrZl3-k0qgt1bmX-4",
                                                    style: {
                                                        height: "100%",
                                                        width: "100%"
                                                    },
                                                    variant: "fg2Qm7JpU",
                                                    width: "100%"
                                                })
                                            })
                                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                            height: 180,
                                            width: "268px",
                                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                                className: "framer-1s29gc2-container",
                                                inComponentSlot: true,
                                                layoutDependency: layoutDependency,
                                                layoutId: "ZLqKTcKTk-ihiVjMx2y-5-container",
                                                nodeId: "ihiVjMx2y",
                                                rendersWithMotion: true,
                                                scopeId: "BmyWZK_C9",
                                                children: /*#__PURE__*/ _jsx(ClientCardXL, {
                                                    height: "100%",
                                                    id: "ihiVjMx2y",
                                                    layoutId: "ZLqKTcKTk-ihiVjMx2y-5",
                                                    Ln8d5mN1s: addImageAlt({
                                                        pixelHeight: 2560,
                                                        pixelWidth: 2560,
                                                        src: "https://framerusercontent.com/images/mxeBVz0DHCJc9MXV8TdlnkYwXdM.jpg?width=2560&height=2560",
                                                        srcSet: "https://framerusercontent.com/images/mxeBVz0DHCJc9MXV8TdlnkYwXdM.jpg?scale-down-to=512&width=2560&height=2560 512w,https://framerusercontent.com/images/mxeBVz0DHCJc9MXV8TdlnkYwXdM.jpg?scale-down-to=1024&width=2560&height=2560 1024w,https://framerusercontent.com/images/mxeBVz0DHCJc9MXV8TdlnkYwXdM.jpg?scale-down-to=2048&width=2560&height=2560 2048w,https://framerusercontent.com/images/mxeBVz0DHCJc9MXV8TdlnkYwXdM.jpg?width=2560&height=2560 2560w"
                                                    }, ""),
                                                    style: {
                                                        height: "100%",
                                                        width: "100%"
                                                    },
                                                    variant: "fg2Qm7JpU",
                                                    width: "100%"
                                                })
                                            })
                                        })],
                                        speed: 50,
                                        style: {
                                            height: "100%",
                                            width: "100%"
                                        },
                                        width: "100%"
                                    })
                                })
                            }), isDisplayed1() && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                    className: "framer-1byfcfc-container",
                                    isAuthoredByUser: true,
                                    isModuleExternal: true,
                                    layoutDependency: layoutDependency,
                                    layoutId: "PTB1JOtlP-container",
                                    nodeId: "PTB1JOtlP",
                                    rendersWithMotion: true,
                                    scopeId: "BmyWZK_C9",
                                    children: /*#__PURE__*/ _jsx(Slideshow, {
                                        alignment: "flex-start",
                                        arrowOptions: {
                                            arrowFill: "rgba(0, 0, 0, 0)",
                                            arrowGap: 30,
                                            arrowPadding: -21,
                                            arrowPaddingBottom: -55,
                                            arrowPaddingLeft: 0,
                                            arrowPaddingRight: 275,
                                            arrowPaddingTop: -70,
                                            arrowPosition: "bottom-right",
                                            arrowRadius: 100,
                                            arrowShouldFadeIn: false,
                                            arrowShouldSpace: false,
                                            arrowSize: 25,
                                            leftArrow: "https://framerusercontent.com/images/kEw1mnXoxbH5B6L1pZTKejD8.svg?width=256&height=256",
                                            rightArrow: "https://framerusercontent.com/images/mOMvmtm0XcmfOgKwLByN9WrE.svg?width=256&height=256",
                                            showMouseControls: false
                                        },
                                        autoPlayControl: true,
                                        borderRadius: 0,
                                        direction: "left",
                                        dragControl: true,
                                        effectsOptions: {
                                            effectsHover: true,
                                            effectsOpacity: .8,
                                            effectsPerspective: 1200,
                                            effectsRotate: 0,
                                            effectsScale: .9,
                                            playOffscreen: false
                                        },
                                        fadeOptions: {
                                            fadeAlpha: 0,
                                            fadeContent: false,
                                            fadeInset: 0,
                                            fadeWidth: 25,
                                            overflow: true
                                        },
                                        gap: 20,
                                        height: "100%",
                                        id: "PTB1JOtlP",
                                        intervalControl: 3,
                                        itemAmount: 1,
                                        layoutId: "PTB1JOtlP",
                                        padding: 20,
                                        paddingBottom: 50,
                                        paddingLeft: 20,
                                        paddingPerSide: true,
                                        paddingRight: 20,
                                        paddingTop: 0,
                                        progressOptions: {
                                            dotsActiveOpacity: 1,
                                            dotsBackground: "var(--token-fb12e452-5cc0-4bf6-a721-de659eb1ddc7, rgb(245, 244, 243))",
                                            dotsBlur: 0,
                                            dotsFill: "var(--token-f79d02c7-1774-42e8-8ffe-88585b6d572d, rgb(30, 30, 30))",
                                            dotsGap: 10,
                                            dotsInset: 0,
                                            dotSize: 10,
                                            dotsOpacity: .5,
                                            dotsPadding: 10,
                                            dotsRadius: 50,
                                            showProgressDots: true
                                        },
                                        slots: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                            height: 180,
                                            width: "268px",
                                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                                className: "framer-jn1a0j-container",
                                                inComponentSlot: true,
                                                layoutDependency: layoutDependency,
                                                layoutId: "pTIcMFXB_-Uyin_DcTz-0-container",
                                                nodeId: "Uyin_DcTz",
                                                rendersWithMotion: true,
                                                scopeId: "BmyWZK_C9",
                                                children: /*#__PURE__*/ _jsx(ClientCardXL, {
                                                    height: "100%",
                                                    id: "Uyin_DcTz",
                                                    layoutId: "pTIcMFXB_-Uyin_DcTz-0",
                                                    Ln8d5mN1s: addImageAlt({
                                                        pixelHeight: 2560,
                                                        pixelWidth: 2560,
                                                        src: "https://framerusercontent.com/images/nvwMzGj6it9ES02wDvpqv67cBa0.jpg?width=2560&height=2560",
                                                        srcSet: "https://framerusercontent.com/images/nvwMzGj6it9ES02wDvpqv67cBa0.jpg?scale-down-to=512&width=2560&height=2560 512w,https://framerusercontent.com/images/nvwMzGj6it9ES02wDvpqv67cBa0.jpg?scale-down-to=1024&width=2560&height=2560 1024w,https://framerusercontent.com/images/nvwMzGj6it9ES02wDvpqv67cBa0.jpg?scale-down-to=2048&width=2560&height=2560 2048w,https://framerusercontent.com/images/nvwMzGj6it9ES02wDvpqv67cBa0.jpg?width=2560&height=2560 2560w"
                                                    }, ""),
                                                    style: {
                                                        height: "100%",
                                                        width: "100%"
                                                    },
                                                    variant: "fg2Qm7JpU",
                                                    width: "100%"
                                                })
                                            })
                                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                            height: 180,
                                            width: "268px",
                                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                                className: "framer-mafozn-container",
                                                inComponentSlot: true,
                                                layoutDependency: layoutDependency,
                                                layoutId: "XVmxK_S6E-RuAYmxpGF-1-container",
                                                nodeId: "RuAYmxpGF",
                                                rendersWithMotion: true,
                                                scopeId: "BmyWZK_C9",
                                                children: /*#__PURE__*/ _jsx(ClientCardXL, {
                                                    height: "100%",
                                                    id: "RuAYmxpGF",
                                                    layoutId: "XVmxK_S6E-RuAYmxpGF-1",
                                                    Ln8d5mN1s: addImageAlt({
                                                        pixelHeight: 2560,
                                                        pixelWidth: 2560,
                                                        src: "https://framerusercontent.com/images/2HNBj8EpPhWYN2mTxm1qVqTjEY.jpg?width=2560&height=2560",
                                                        srcSet: "https://framerusercontent.com/images/2HNBj8EpPhWYN2mTxm1qVqTjEY.jpg?scale-down-to=512&width=2560&height=2560 512w,https://framerusercontent.com/images/2HNBj8EpPhWYN2mTxm1qVqTjEY.jpg?scale-down-to=1024&width=2560&height=2560 1024w,https://framerusercontent.com/images/2HNBj8EpPhWYN2mTxm1qVqTjEY.jpg?scale-down-to=2048&width=2560&height=2560 2048w,https://framerusercontent.com/images/2HNBj8EpPhWYN2mTxm1qVqTjEY.jpg?width=2560&height=2560 2560w"
                                                    }, ""),
                                                    style: {
                                                        height: "100%",
                                                        width: "100%"
                                                    },
                                                    variant: "fg2Qm7JpU",
                                                    width: "100%"
                                                })
                                            })
                                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                            height: 180,
                                            width: "268px",
                                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                                className: "framer-c6x870-container",
                                                inComponentSlot: true,
                                                layoutDependency: layoutDependency,
                                                layoutId: "TcGjAZkhv-Mi4OukAXW-2-container",
                                                nodeId: "Mi4OukAXW",
                                                rendersWithMotion: true,
                                                scopeId: "BmyWZK_C9",
                                                children: /*#__PURE__*/ _jsx(ClientCardXL, {
                                                    height: "100%",
                                                    id: "Mi4OukAXW",
                                                    layoutId: "TcGjAZkhv-Mi4OukAXW-2",
                                                    Ln8d5mN1s: addImageAlt({
                                                        pixelHeight: 2560,
                                                        pixelWidth: 2560,
                                                        src: "https://framerusercontent.com/images/eg04bFcNkzl2gTkfiGuozksUGY.jpg?width=2560&height=2560",
                                                        srcSet: "https://framerusercontent.com/images/eg04bFcNkzl2gTkfiGuozksUGY.jpg?scale-down-to=512&width=2560&height=2560 512w,https://framerusercontent.com/images/eg04bFcNkzl2gTkfiGuozksUGY.jpg?scale-down-to=1024&width=2560&height=2560 1024w,https://framerusercontent.com/images/eg04bFcNkzl2gTkfiGuozksUGY.jpg?scale-down-to=2048&width=2560&height=2560 2048w,https://framerusercontent.com/images/eg04bFcNkzl2gTkfiGuozksUGY.jpg?width=2560&height=2560 2560w"
                                                    }, ""),
                                                    style: {
                                                        height: "100%",
                                                        width: "100%"
                                                    },
                                                    variant: "fg2Qm7JpU",
                                                    width: "100%"
                                                })
                                            })
                                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                            height: 180,
                                            width: "268px",
                                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                                className: "framer-1r11zxw-container",
                                                inComponentSlot: true,
                                                layoutDependency: layoutDependency,
                                                layoutId: "f46u4W9ca-rra3Z9qby-3-container",
                                                nodeId: "rra3Z9qby",
                                                rendersWithMotion: true,
                                                scopeId: "BmyWZK_C9",
                                                children: /*#__PURE__*/ _jsx(ClientCardXL, {
                                                    height: "100%",
                                                    id: "rra3Z9qby",
                                                    layoutId: "f46u4W9ca-rra3Z9qby-3",
                                                    Ln8d5mN1s: addImageAlt({
                                                        pixelHeight: 2560,
                                                        pixelWidth: 2560,
                                                        src: "https://framerusercontent.com/images/8E2TKSLPqKIJEpS6e3x1ChI3Wk.jpg?width=2560&height=2560",
                                                        srcSet: "https://framerusercontent.com/images/8E2TKSLPqKIJEpS6e3x1ChI3Wk.jpg?scale-down-to=512&width=2560&height=2560 512w,https://framerusercontent.com/images/8E2TKSLPqKIJEpS6e3x1ChI3Wk.jpg?scale-down-to=1024&width=2560&height=2560 1024w,https://framerusercontent.com/images/8E2TKSLPqKIJEpS6e3x1ChI3Wk.jpg?scale-down-to=2048&width=2560&height=2560 2048w,https://framerusercontent.com/images/8E2TKSLPqKIJEpS6e3x1ChI3Wk.jpg?width=2560&height=2560 2560w"
                                                    }, ""),
                                                    style: {
                                                        height: "100%",
                                                        width: "100%"
                                                    },
                                                    variant: "fg2Qm7JpU",
                                                    width: "100%"
                                                })
                                            })
                                        }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                            height: 180,
                                            width: "268px",
                                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                                className: "framer-3kap1u-container",
                                                inComponentSlot: true,
                                                layoutDependency: layoutDependency,
                                                layoutId: "t6KSNAsDh-nIfSlBYPF-4-container",
                                                nodeId: "nIfSlBYPF",
                                                rendersWithMotion: true,
                                                scopeId: "BmyWZK_C9",
                                                children: /*#__PURE__*/ _jsx(ClientCardXL, {
                                                    height: "100%",
                                                    id: "nIfSlBYPF",
                                                    layoutId: "t6KSNAsDh-nIfSlBYPF-4",
                                                    Ln8d5mN1s: addImageAlt({
                                                        pixelHeight: 2560,
                                                        pixelWidth: 2560,
                                                        src: "https://framerusercontent.com/images/mxeBVz0DHCJc9MXV8TdlnkYwXdM.jpg?width=2560&height=2560",
                                                        srcSet: "https://framerusercontent.com/images/mxeBVz0DHCJc9MXV8TdlnkYwXdM.jpg?scale-down-to=512&width=2560&height=2560 512w,https://framerusercontent.com/images/mxeBVz0DHCJc9MXV8TdlnkYwXdM.jpg?scale-down-to=1024&width=2560&height=2560 1024w,https://framerusercontent.com/images/mxeBVz0DHCJc9MXV8TdlnkYwXdM.jpg?scale-down-to=2048&width=2560&height=2560 2048w,https://framerusercontent.com/images/mxeBVz0DHCJc9MXV8TdlnkYwXdM.jpg?width=2560&height=2560 2560w"
                                                    }, ""),
                                                    style: {
                                                        height: "100%",
                                                        width: "100%"
                                                    },
                                                    variant: "fg2Qm7JpU",
                                                    width: "100%"
                                                })
                                            })
                                        })],
                                        startFrom: 0,
                                        style: {
                                            height: "100%",
                                            width: "100%"
                                        },
                                        transitionControl: {
                                            damping: 40,
                                            delay: 0,
                                            mass: 1,
                                            stiffness: 200,
                                            type: "spring"
                                        },
                                        width: "100%"
                                    })
                                })
                            }), isDisplayed() && /*#__PURE__*/ _jsx(motion.div, {
                                className: "framer-j8uqrr",
                                "data-framer-name": "Line",
                                layoutDependency: layoutDependency,
                                layoutId: "jvEStsDSN",
                                style: {
                                    backgroundColor: "var(--token-bf3b78f1-7c89-4ecd-bba4-77c1a4c7b347, rgb(234, 234, 234))",
                                    opacity: .65
                                }
                            }), /*#__PURE__*/ _jsx(AnimatePresence, {
                                children: overlay.visible && /*#__PURE__*/ _jsx(Floating, {
                                    alignment: "center",
                                    anchorRef: refBinding,
                                    className: cx(scopingClassNames, classNames),
                                    collisionDetection: true,
                                    collisionDetectionPadding: 20,
                                    "data-framer-portal-id": `${layoutId}-1gghnu2`,
                                    offsetX: 0,
                                    offsetY: 10,
                                    onDismiss: overlay.hide,
                                    placement: "bottom",
                                    safeArea: true,
                                    zIndex: 11,
                                    children: /*#__PURE__*/ _jsx(MotionDivWithFX, {
                                        __perspectiveFX: false,
                                        __smartComponentFX: true,
                                        __targetOpacity: 1,
                                        animate: animation1,
                                        className: "framer-1oxemt7",
                                        exit: animation,
                                        initial: animation2,
                                        layoutDependency: layoutDependency,
                                        layoutId: "gPiF_jxQs",
                                        ref: ref1,
                                        role: "dialog",
                                        style: {
                                            backgroundColor: "rgb(255, 255, 255)",
                                            borderBottomLeftRadius: 10,
                                            borderBottomRightRadius: 10,
                                            borderTopLeftRadius: 10,
                                            borderTopRightRadius: 10,
                                            boxShadow: "0px 10px 20px 0px rgba(0, 0, 0, 0.05)"
                                        }
                                    })
                                })
                            })]
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-8OLiA.framer-1rpt4uu, .framer-8OLiA .framer-1rpt4uu { display: block; }", ".framer-8OLiA.framer-1gghnu2 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1440px; }", ".framer-8OLiA .framer-7optrw, .framer-8OLiA .framer-j8uqrr { flex: none; height: 1px; position: relative; width: 100%; }", ".framer-8OLiA .framer-129g3z6-container { flex: none; height: 180px; position: relative; width: 100%; }", ".framer-8OLiA .framer-jn1a0j-container, .framer-8OLiA .framer-rrowkn-container, .framer-8OLiA .framer-x106js-container, .framer-8OLiA .framer-66sskk-container, .framer-8OLiA .framer-1s29gc2-container, .framer-8OLiA .framer-mafozn-container, .framer-8OLiA .framer-c6x870-container, .framer-8OLiA .framer-1r11zxw-container, .framer-8OLiA .framer-3kap1u-container { height: 180px; position: relative; width: 268px; }", ".framer-8OLiA .framer-1byfcfc-container { flex: none; height: 240px; position: relative; width: 100%; z-index: 2; }", ".framer-8OLiA .framer-1oxemt7 { height: 150px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 200px; will-change: var(--framer-will-change-override, transform); }", ".framer-8OLiA.framer-v-1qckcgx.framer-1gghnu2 { gap: 30px; width: 390px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 182
 * @framerIntrinsicWidth 1440
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"BbZ4PDuqX":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerBmyWZK_C9 = withCSS(Component, css, "framer-8OLiA");
export default FramerBmyWZK_C9;
FramerBmyWZK_C9.displayName = "Client Section XL";
FramerBmyWZK_C9.defaultProps = {
    height: 182,
    width: 1440
};
addPropertyControls(FramerBmyWZK_C9, {
    variant: {
        options: ["YmEHXmhgM", "BbZ4PDuqX"],
        optionTitles: ["Ticker", "Slider"],
        title: "Variant",
        type: ControlType.Enum
    }
});
addFonts(FramerBmyWZK_C9, [{
    explicitInter: true,
    fonts: []
}, ...ClientCardXLFonts, ...TickerFonts, ...SlideshowFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerBmyWZK_C9",
            "slots": [],
            "annotations": {
                "framerComponentViewportWidth": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"BbZ4PDuqX\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerContractVersion": "1",
                "framerIntrinsicHeight": "182",
                "framerIntrinsicWidth": "1440",
                "framerDisplayContentsDiv": "false",
                "framerImmutableVariables": "true",
                "framerAutoSizeImages": "true",
                "framerColorSyntax": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./BmyWZK_C9.map