// Generated by Framer (4d22d44)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-R_6RUHbTl", breakpoints: [{hash: "e0ajr3"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-SFtYv", title: siteMetadata(params, activeLocale).title || "Dark Work", viewport: "width=1440"}
}

export const metadataVersion = 1