// Generated by Framer (24e7187)
import {
    addPropertyControls as e,
    ControlType as l,
    QueryCache as a,
    QueryEngine as r
} from "framer";
import {
    DatabaseCollection as t,
    DatabaseDictionaryIndex as m
} from "./LH_pkMQDd-0.js";
import {
    getRichTextJsonResolver as o
} from "./LH_pkMQDd-1.js";
let c = {
        aj5Onj2wB: {
            isNullable: !0,
            type: l.String
        },
        createdAt: {
            isNullable: !0,
            type: l.Date
        },
        CzggB1wSi: {
            isNullable: !0,
            type: l.RichText
        },
        d500MXEd6: {
            isNullable: !0,
            type: l.String
        },
        dEkErz2Py: {
            isNullable: !0,
            type: l.String
        },
        FLjpxs6UP: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        gSViQRiAn: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        id: {
            isNullable: !1,
            type: l.String
        },
        K_pl3HZYi: {
            isNullable: !0,
            type: l.String
        },
        kcrgW1AW8: {
            isNullable: !0,
            type: l.RichText
        },
        LA28aoJte: {
            isNullable: !0,
            type: l.RichText
        },
        LTZnKGZVg: {
            isNullable: !0,
            type: l.Date
        },
        mKasZUkWD: {
            isNullable: !0,
            type: l.String
        },
        nextItemId: {
            isNullable: !0,
            type: l.String
        },
        p5Kkpdp88: {
            isNullable: !0,
            type: l.String
        },
        previousItemId: {
            isNullable: !0,
            type: l.String
        },
        rf43RcEcl: {
            isNullable: !0,
            type: l.RichText
        },
        tINCAAUZG: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        u6njdxlhn: {
            isNullable: !0,
            type: l.RichText
        },
        updatedAt: {
            isNullable: !0,
            type: l.Date
        },
        uZ4gTm4h9: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        wRILY1NDw: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        x0P7Nh0qj: {
            isNullable: !0,
            type: l.String
        },
        XC1Kdvih6: {
            isNullable: !0,
            type: l.String
        },
        xFJtjY01q: {
            isNullable: !0,
            type: l.RichText
        },
        Y0j_qmQ5f: {
            isNullable: !0,
            type: l.RichText
        }
    },
    n = ["id"],
    i = {
        type: 1
    },
    s = ["previousItemId"],
    d = ["nextItemId"],
    u = ["id", "mKasZUkWD"],
    f = ["mKasZUkWD", "id"],
    p = ["mKasZUkWD"],
    h = {
        type: 0
    },
    L = ["uZ4gTm4h9"],
    w = ["LTZnKGZVg"],
    U = ["aj5Onj2wB"],
    g = ["Y0j_qmQ5f"],
    x = ["d500MXEd6"],
    R = ["XC1Kdvih6"],
    N = ["dEkErz2Py"],
    y = ["x0P7Nh0qj"],
    S = ["kcrgW1AW8"],
    D = ["LA28aoJte"],
    k = ["tINCAAUZG"],
    Q = ["K_pl3HZYi"],
    _ = ["CzggB1wSi"],
    H = ["xFJtjY01q"],
    M = ["gSViQRiAn"],
    I = ["FLjpxs6UP"],
    E = ["p5Kkpdp88"],
    b = ["u6njdxlhn"],
    T = ["rf43RcEcl"],
    V = ["wRILY1NDw"],
    j = [],
    Z = e => {
        let l = j[e];
        if (l) return l().then(e => e.default);
    },
    v = {},
    A = o(v),
    K = new r,
    B = new a(K),
    C = {
        collectionByLocaleId: {
            default: new t({
                chunks: [new URL("./LH_pkMQDd-chunk-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")],
                indexes: [new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: n,
                    range: {
                        from: 0,
                        to: 97
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: s,
                    range: {
                        from: 97,
                        to: 193
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: d,
                    range: {
                        from: 193,
                        to: 285
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: u,
                    range: {
                        from: 285,
                        to: 459
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: f,
                    range: {
                        from: 459,
                        to: 633
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: p,
                    range: {
                        from: 633,
                        to: 759
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: L,
                    range: {
                        from: 759,
                        to: 2201
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: w,
                    range: {
                        from: 2201,
                        to: 2290
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: U,
                    range: {
                        from: 2290,
                        to: 2406
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: g,
                    range: {
                        from: 2406,
                        to: 2956
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: x,
                    range: {
                        from: 2956,
                        to: 3097
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: R,
                    range: {
                        from: 3097,
                        to: 3189
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: N,
                    range: {
                        from: 3189,
                        to: 3283
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: y,
                    range: {
                        from: 3283,
                        to: 3385
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: S,
                    range: {
                        from: 3385,
                        to: 3993
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: D,
                    range: {
                        from: 3993,
                        to: 7344
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: k,
                    range: {
                        from: 7344,
                        to: 8563
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: Q,
                    range: {
                        from: 8563,
                        to: 8671
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: _,
                    range: {
                        from: 8671,
                        to: 9276
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: H,
                    range: {
                        from: 9276,
                        to: 12462
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: M,
                    range: {
                        from: 12462,
                        to: 13678
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: I,
                    range: {
                        from: 13678,
                        to: 14900
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: E,
                    range: {
                        from: 14900,
                        to: 15007
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: b,
                    range: {
                        from: 15007,
                        to: 15637
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: T,
                    range: {
                        from: 15637,
                        to: 18819
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: V,
                    range: {
                        from: 18819,
                        to: 20155
                    },
                    url: new URL("./LH_pkMQDd-indexes-default-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                })],
                resolveRichText: A,
                resolveVectorSetItem: Z,
                schema: c
            }),
            E65nUUcaa: new t({
                chunks: [new URL("./LH_pkMQDd-chunk-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")],
                indexes: [new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: n,
                    range: {
                        from: 0,
                        to: 97
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: s,
                    range: {
                        from: 97,
                        to: 193
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: d,
                    range: {
                        from: 193,
                        to: 285
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: u,
                    range: {
                        from: 285,
                        to: 459
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: f,
                    range: {
                        from: 459,
                        to: 633
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: p,
                    range: {
                        from: 633,
                        to: 759
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: L,
                    range: {
                        from: 759,
                        to: 2201
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: w,
                    range: {
                        from: 2201,
                        to: 2290
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: U,
                    range: {
                        from: 2290,
                        to: 2406
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: g,
                    range: {
                        from: 2406,
                        to: 2956
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: x,
                    range: {
                        from: 2956,
                        to: 3081
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: R,
                    range: {
                        from: 3081,
                        to: 3182
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: N,
                    range: {
                        from: 3182,
                        to: 3278
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: y,
                    range: {
                        from: 3278,
                        to: 3382
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: S,
                    range: {
                        from: 3382,
                        to: 3990
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: D,
                    range: {
                        from: 3990,
                        to: 7341
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: k,
                    range: {
                        from: 7341,
                        to: 8560
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: Q,
                    range: {
                        from: 8560,
                        to: 8668
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: _,
                    range: {
                        from: 8668,
                        to: 9273
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: H,
                    range: {
                        from: 9273,
                        to: 12459
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: M,
                    range: {
                        from: 12459,
                        to: 13675
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: I,
                    range: {
                        from: 13675,
                        to: 14897
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: E,
                    range: {
                        from: 14897,
                        to: 15005
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: b,
                    range: {
                        from: 15005,
                        to: 15635
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: T,
                    range: {
                        from: 15635,
                        to: 18817
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                }), new m({
                    collation: h,
                    collectionSchema: c,
                    fieldNames: V,
                    range: {
                        from: 18817,
                        to: 20153
                    },
                    url: new URL("./LH_pkMQDd-indexes-E65nUUcaa-0.framercms", "https://framerusercontent.com/modules/oNknBobTw8bW6XxqshlQ/KTfxAvupwlCZ9CfTUSNI/LH_pkMQDd.js").href.replace("/modules/", "/cms/")
                })],
                resolveRichText: A,
                resolveVectorSetItem: Z,
                schema: c
            })
        },
        displayName: "Blog Detail"
    };
export default C;
e(C, {
    mKasZUkWD: {
        title: "Slug",
        type: l.String
    },
    uZ4gTm4h9: {
        title: "Preview Image",
        type: l.ResponsiveImage
    },
    LTZnKGZVg: {
        title: "Date",
        type: l.Date
    },
    aj5Onj2wB: {
        defaultValue: "",
        title: "Title",
        type: l.String
    },
    Y0j_qmQ5f: {
        defaultValue: "",
        title: "Body Text",
        type: l.RichText
    },
    d500MXEd6: {
        defaultValue: "",
        title: "Category",
        type: l.String
    },
    XC1Kdvih6: {
        defaultValue: "",
        title: "Tag 1",
        type: l.String
    },
    dEkErz2Py: {
        defaultValue: "",
        title: "Tag 2",
        type: l.String
    },
    x0P7Nh0qj: {
        defaultValue: "",
        title: "Subtitle 1",
        type: l.String
    },
    kcrgW1AW8: {
        defaultValue: "",
        title: "Description",
        type: l.RichText
    },
    LA28aoJte: {
        defaultValue: "",
        title: "Body Text",
        type: l.RichText
    },
    tINCAAUZG: {
        title: "Image 1",
        type: l.ResponsiveImage
    },
    K_pl3HZYi: {
        defaultValue: "",
        title: "Subtitle 2",
        type: l.String
    },
    CzggB1wSi: {
        defaultValue: "",
        title: "Description",
        type: l.RichText
    },
    xFJtjY01q: {
        defaultValue: "",
        title: "Body Text",
        type: l.RichText
    },
    gSViQRiAn: {
        title: "Image 2",
        type: l.ResponsiveImage
    },
    FLjpxs6UP: {
        title: "Image 3",
        type: l.ResponsiveImage
    },
    p5Kkpdp88: {
        defaultValue: "",
        title: "Subtitle 3",
        type: l.String
    },
    u6njdxlhn: {
        defaultValue: "",
        title: "Description",
        type: l.RichText
    },
    rf43RcEcl: {
        defaultValue: "",
        title: "Body Text",
        type: l.RichText
    },
    wRILY1NDw: {
        title: "Image 4",
        type: l.ResponsiveImage
    },
    createdAt: {
        title: "Created",
        type: l.Date
    },
    updatedAt: {
        title: "Updated",
        type: l.Date
    },
    previousItemId: {
        dataIdentifier: "local-module:collection/LH_pkMQDd:default",
        title: "Previous",
        type: l.CollectionReference
    },
    nextItemId: {
        dataIdentifier: "local-module:collection/LH_pkMQDd:default",
        title: "Next",
        type: l.CollectionReference
    }
});
export const enumToDisplayNameFunctions = {};
export const utils = {
    async getSlugByRecordId(e, l) {
        let [a] = await B.get({
            from: {
                data: C,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "mKasZUkWD",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "id",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l).readAsync();
        return a ? .mKasZUkWD;
    },
    async getRecordIdBySlug(e, l) {
        let [a] = await B.get({
            from: {
                data: C,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "id",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "mKasZUkWD",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l).readAsync();
        return a ? .id;
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "data",
            "name": "data",
            "annotations": {
                "framerCollectionId": "LH_pkMQDd",
                "framerEnumToDisplayNameUtils": "2",
                "framerAutoSizeImages": "true",
                "framerRecordIdKey": "id",
                "framerSlug": "mKasZUkWD",
                "framerCollectionUtils": "1",
                "framerData": "",
                "framerContractVersion": "1",
                "framerColorSyntax": "false"
            }
        },
        "enumToDisplayNameFunctions": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "utils": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}