// Generated by Framer (c2a8602)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    ResolveLinks,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useRouter,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import getLocalizedValue from "https://framerusercontent.com/modules/NsUYCsIyLHIHsHwwlRLF/OZMv8rdzUd8NzF3JCU0q/uRhkR_1V5.js";
import FooterMenuLink from "https://framerusercontent.com/modules/qLd3zlHSDCoJ5jzstUrf/ysCSQBXGjxdjj0GNAXMM/n0ewr161N.js";
const FooterMenuLinkFonts = getFonts(FooterMenuLink);
const cycleOrder = ["uzEeWtzzm", "NhtjVs_oa", "eEWEObMHH", "T8C0qD4Oz", "Qb5QChcxF", "A6hcQCAd_"];
const serializationHash = "framer-pABg5";
const variantClassNames = {
    A6hcQCAd_: "framer-v-1mgpef4",
    eEWEObMHH: "framer-v-pfwshc",
    NhtjVs_oa: "framer-v-16polh1",
    Qb5QChcxF: "framer-v-19b7jhs",
    T8C0qD4Oz: "framer-v-19ot94d",
    uzEeWtzzm: "framer-v-11uqdgv"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "About Active": "NhtjVs_oa",
    "All In-Active": "A6hcQCAd_",
    "Blog Active": "T8C0qD4Oz",
    "Contact Active": "Qb5QChcxF",
    "Home Active": "uzEeWtzzm",
    "Work Active": "eEWEObMHH"
};
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "uzEeWtzzm"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "uzEeWtzzm",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const router = useRouter();
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-11uqdgv", className, classNames),
                    "data-framer-name": "Home Active",
                    layoutDependency: layoutDependency,
                    layoutId: "uzEeWtzzm",
                    ref: refBinding,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        A6hcQCAd_: {
                            "data-framer-name": "All In-Active"
                        },
                        eEWEObMHH: {
                            "data-framer-name": "Work Active"
                        },
                        NhtjVs_oa: {
                            "data-framer-name": "About Active"
                        },
                        Qb5QChcxF: {
                            "data-framer-name": "Contact Active"
                        },
                        T8C0qD4Oz: {
                            "data-framer-name": "Blog Active"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(ResolveLinks, {
                        links: [{
                            href: {
                                webPageId: "augiA20Il"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "augiA20Il"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "augiA20Il"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "augiA20Il"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "augiA20Il"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "augiA20Il"
                            },
                            implicitPathVariables: undefined
                        }],
                        children: resolvedLinks => /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 48,
                            width: componentViewport ? .width || "100vw",
                            y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 200) - 0 - 240) / 2 + 0 + 0),
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-cyajai-container",
                                layoutDependency: layoutDependency,
                                layoutId: "uES1DUjYf-container",
                                nodeId: "uES1DUjYf",
                                rendersWithMotion: true,
                                scopeId: "uRhkR_1V5",
                                children: /*#__PURE__*/ _jsx(FooterMenuLink, {
                                    cV2MQzo4R: getLocalizedValue("v1", activeLocale) ? ? " Home",
                                    height: "100%",
                                    id: "uES1DUjYf",
                                    layoutId: "uES1DUjYf",
                                    rHTdzion6: getLocalizedValue("v0", activeLocale) ? ? "01 /",
                                    style: {
                                        width: "100%"
                                    },
                                    UBOsZsvBc: resolvedLinks[0],
                                    variant: "YHATSZwFC",
                                    width: "100%",
                                    ...addPropertyOverrides({
                                        A6hcQCAd_: {
                                            UBOsZsvBc: resolvedLinks[5],
                                            variant: "bod5trLRB"
                                        },
                                        eEWEObMHH: {
                                            UBOsZsvBc: resolvedLinks[2],
                                            variant: "bod5trLRB"
                                        },
                                        NhtjVs_oa: {
                                            UBOsZsvBc: resolvedLinks[1],
                                            variant: "bod5trLRB"
                                        },
                                        Qb5QChcxF: {
                                            UBOsZsvBc: resolvedLinks[4],
                                            variant: "bod5trLRB"
                                        },
                                        T8C0qD4Oz: {
                                            UBOsZsvBc: resolvedLinks[3],
                                            variant: "bod5trLRB"
                                        }
                                    }, baseVariant, gestureVariant)
                                })
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ResolveLinks, {
                        links: [{
                            href: {
                                webPageId: "do537ZQkd"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "do537ZQkd"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "do537ZQkd"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "do537ZQkd"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "do537ZQkd"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "do537ZQkd"
                            },
                            implicitPathVariables: undefined
                        }],
                        children: resolvedLinks1 => /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 48,
                            width: componentViewport ? .width || "100vw",
                            y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 200) - 0 - 240) / 2 + 48 + 0),
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-1osfon2-container",
                                layoutDependency: layoutDependency,
                                layoutId: "U8UvlHM8T-container",
                                nodeId: "U8UvlHM8T",
                                rendersWithMotion: true,
                                scopeId: "uRhkR_1V5",
                                children: /*#__PURE__*/ _jsx(FooterMenuLink, {
                                    cV2MQzo4R: getLocalizedValue("v3", activeLocale) ? ? " About",
                                    height: "100%",
                                    id: "U8UvlHM8T",
                                    layoutId: "U8UvlHM8T",
                                    rHTdzion6: getLocalizedValue("v2", activeLocale) ? ? "02 /",
                                    style: {
                                        width: "100%"
                                    },
                                    UBOsZsvBc: resolvedLinks1[0],
                                    variant: "YcP4kjqKM",
                                    width: "100%",
                                    ...addPropertyOverrides({
                                        A6hcQCAd_: {
                                            UBOsZsvBc: resolvedLinks1[5]
                                        },
                                        eEWEObMHH: {
                                            UBOsZsvBc: resolvedLinks1[2]
                                        },
                                        NhtjVs_oa: {
                                            UBOsZsvBc: resolvedLinks1[1],
                                            variant: "YfKPH2cMT"
                                        },
                                        Qb5QChcxF: {
                                            UBOsZsvBc: resolvedLinks1[4]
                                        },
                                        T8C0qD4Oz: {
                                            UBOsZsvBc: resolvedLinks1[3]
                                        }
                                    }, baseVariant, gestureVariant)
                                })
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ResolveLinks, {
                        links: [{
                            href: {
                                webPageId: "AkOIicI1y"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "AkOIicI1y"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "AkOIicI1y"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "AkOIicI1y"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "AkOIicI1y"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "AkOIicI1y"
                            },
                            implicitPathVariables: undefined
                        }],
                        children: resolvedLinks2 => /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 48,
                            width: componentViewport ? .width || "100vw",
                            y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 200) - 0 - 240) / 2 + 96 + 0),
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-m07xft-container",
                                layoutDependency: layoutDependency,
                                layoutId: "qxfpbzGp8-container",
                                nodeId: "qxfpbzGp8",
                                rendersWithMotion: true,
                                scopeId: "uRhkR_1V5",
                                children: /*#__PURE__*/ _jsx(FooterMenuLink, {
                                    cV2MQzo4R: getLocalizedValue("v5", activeLocale) ? ? " Work",
                                    height: "100%",
                                    id: "qxfpbzGp8",
                                    layoutId: "qxfpbzGp8",
                                    rHTdzion6: getLocalizedValue("v4", activeLocale) ? ? "03 /",
                                    style: {
                                        width: "100%"
                                    },
                                    UBOsZsvBc: resolvedLinks2[0],
                                    variant: "YcP4kjqKM",
                                    width: "100%",
                                    ...addPropertyOverrides({
                                        A6hcQCAd_: {
                                            UBOsZsvBc: resolvedLinks2[5]
                                        },
                                        eEWEObMHH: {
                                            UBOsZsvBc: resolvedLinks2[2],
                                            variant: "YfKPH2cMT"
                                        },
                                        NhtjVs_oa: {
                                            UBOsZsvBc: resolvedLinks2[1]
                                        },
                                        Qb5QChcxF: {
                                            UBOsZsvBc: resolvedLinks2[4]
                                        },
                                        T8C0qD4Oz: {
                                            UBOsZsvBc: resolvedLinks2[3]
                                        }
                                    }, baseVariant, gestureVariant)
                                })
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ResolveLinks, {
                        links: [{
                            href: {
                                webPageId: "uVdpZqf_w"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "uVdpZqf_w"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "uVdpZqf_w"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "uVdpZqf_w"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "uVdpZqf_w"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "uVdpZqf_w"
                            },
                            implicitPathVariables: undefined
                        }],
                        children: resolvedLinks3 => /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 48,
                            width: componentViewport ? .width || "100vw",
                            y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 200) - 0 - 240) / 2 + 144 + 0),
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-gsf6b2-container",
                                layoutDependency: layoutDependency,
                                layoutId: "fbPX5N0rx-container",
                                nodeId: "fbPX5N0rx",
                                rendersWithMotion: true,
                                scopeId: "uRhkR_1V5",
                                children: /*#__PURE__*/ _jsx(FooterMenuLink, {
                                    cV2MQzo4R: getLocalizedValue("v7", activeLocale) ? ? " Insights",
                                    height: "100%",
                                    id: "fbPX5N0rx",
                                    layoutId: "fbPX5N0rx",
                                    rHTdzion6: getLocalizedValue("v6", activeLocale) ? ? "04 /",
                                    style: {
                                        width: "100%"
                                    },
                                    UBOsZsvBc: resolvedLinks3[0],
                                    variant: "YcP4kjqKM",
                                    width: "100%",
                                    ...addPropertyOverrides({
                                        A6hcQCAd_: {
                                            UBOsZsvBc: resolvedLinks3[5]
                                        },
                                        eEWEObMHH: {
                                            UBOsZsvBc: resolvedLinks3[2]
                                        },
                                        NhtjVs_oa: {
                                            UBOsZsvBc: resolvedLinks3[1]
                                        },
                                        Qb5QChcxF: {
                                            UBOsZsvBc: resolvedLinks3[4]
                                        },
                                        T8C0qD4Oz: {
                                            UBOsZsvBc: resolvedLinks3[3],
                                            variant: "YfKPH2cMT"
                                        }
                                    }, baseVariant, gestureVariant)
                                })
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ResolveLinks, {
                        links: [{
                            href: {
                                webPageId: "v1MMai_cu"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "v1MMai_cu"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "v1MMai_cu"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "v1MMai_cu"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "v1MMai_cu"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "v1MMai_cu"
                            },
                            implicitPathVariables: undefined
                        }],
                        children: resolvedLinks4 => /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 48,
                            width: componentViewport ? .width || "100vw",
                            y: (componentViewport ? .y || 0) + 0 + (((componentViewport ? .height || 200) - 0 - 240) / 2 + 192 + 0),
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-pi5y5r-container",
                                layoutDependency: layoutDependency,
                                layoutId: "z1vp2v9_G-container",
                                nodeId: "z1vp2v9_G",
                                rendersWithMotion: true,
                                scopeId: "uRhkR_1V5",
                                children: /*#__PURE__*/ _jsx(FooterMenuLink, {
                                    cV2MQzo4R: getLocalizedValue("v9", activeLocale) ? ? " Contact",
                                    height: "100%",
                                    id: "z1vp2v9_G",
                                    layoutId: "z1vp2v9_G",
                                    rHTdzion6: getLocalizedValue("v8", activeLocale) ? ? "05 /",
                                    style: {
                                        width: "100%"
                                    },
                                    UBOsZsvBc: resolvedLinks4[0],
                                    variant: "YcP4kjqKM",
                                    width: "100%",
                                    ...addPropertyOverrides({
                                        A6hcQCAd_: {
                                            UBOsZsvBc: resolvedLinks4[5]
                                        },
                                        eEWEObMHH: {
                                            UBOsZsvBc: resolvedLinks4[2]
                                        },
                                        NhtjVs_oa: {
                                            UBOsZsvBc: resolvedLinks4[1]
                                        },
                                        Qb5QChcxF: {
                                            UBOsZsvBc: resolvedLinks4[4],
                                            variant: "YfKPH2cMT"
                                        },
                                        T8C0qD4Oz: {
                                            UBOsZsvBc: resolvedLinks4[3]
                                        }
                                    }, baseVariant, gestureVariant)
                                })
                            })
                        })
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-pABg5.framer-4tcfmm, .framer-pABg5 .framer-4tcfmm { display: block; }", ".framer-pABg5.framer-11uqdgv { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 454px; }", ".framer-pABg5 .framer-cyajai-container, .framer-pABg5 .framer-1osfon2-container, .framer-pABg5 .framer-m07xft-container, .framer-pABg5 .framer-gsf6b2-container, .framer-pABg5 .framer-pi5y5r-container { flex: none; height: auto; position: relative; width: 100%; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 240
 * @framerIntrinsicWidth 454
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"NhtjVs_oa":{"layout":["fixed","auto"]},"eEWEObMHH":{"layout":["fixed","auto"]},"T8C0qD4Oz":{"layout":["fixed","auto"]},"Qb5QChcxF":{"layout":["fixed","auto"]},"A6hcQCAd_":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FrameruRhkR_1V5 = withCSS(Component, css, "framer-pABg5");
export default FrameruRhkR_1V5;
FrameruRhkR_1V5.displayName = "Footer Menu";
FrameruRhkR_1V5.defaultProps = {
    height: 240,
    width: 454
};
addPropertyControls(FrameruRhkR_1V5, {
    variant: {
        options: ["uzEeWtzzm", "NhtjVs_oa", "eEWEObMHH", "T8C0qD4Oz", "Qb5QChcxF", "A6hcQCAd_"],
        optionTitles: ["Home Active", "About Active", "Work Active", "Blog Active", "Contact Active", "All In-Active"],
        title: "Variant",
        type: ControlType.Enum
    }
});
addFonts(FrameruRhkR_1V5, [{
    explicitInter: true,
    fonts: []
}, ...FooterMenuLinkFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FrameruRhkR_1V5",
            "slots": [],
            "annotations": {
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"NhtjVs_oa\":{\"layout\":[\"fixed\",\"auto\"]},\"eEWEObMHH\":{\"layout\":[\"fixed\",\"auto\"]},\"T8C0qD4Oz\":{\"layout\":[\"fixed\",\"auto\"]},\"Qb5QChcxF\":{\"layout\":[\"fixed\",\"auto\"]},\"A6hcQCAd_\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerContractVersion": "1",
                "framerIntrinsicWidth": "454",
                "framerIntrinsicHeight": "240",
                "framerAutoSizeImages": "true",
                "framerComponentViewportWidth": "true",
                "framerColorSyntax": "true",
                "framerDisplayContentsDiv": "false",
                "framerImmutableVariables": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./uRhkR_1V5.map