// Generated by Framer (48da836)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    getFontsFromSharedStyle,
    getPropertyControls,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    Icon as Phosphor
} from "https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/p8dptk4UIND8hbFWz9V7/Phosphor.js";
import * as sharedStyle from "https://framerusercontent.com/modules/cGr2zBmsbU7ooi3EJKS2/1VtvkZOvMtxouyfnbQKS/gNF6pTLez.js";
import * as sharedStyle1 from "https://framerusercontent.com/modules/cfTtitP9DDFrs6NMdFms/mqEfNJk8NPQe8uswiF7n/Ix2IT3vgs.js";
const PhosphorFonts = getFonts(Phosphor);
const PhosphorControls = getPropertyControls(Phosphor);
const cycleOrder = ["m_aYOKqi1", "MVWia3KhW", "GoIavZiTY"];
const serializationHash = "framer-zI5ou";
const variantClassNames = {
    GoIavZiTY: "framer-v-kua66c",
    m_aYOKqi1: "framer-v-1prusa0",
    MVWia3KhW: "framer-v-suq7t2"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Primary: "m_aYOKqi1",
    Secondary: "MVWia3KhW",
    Tertiary: "GoIavZiTY"
};
const getProps = ({
    color,
    height,
    icon,
    id,
    text,
    width,
    ...props
}) => {
    return { ...props,
        a4GwngYzZ: text ? ? props.a4GwngYzZ ? ? "One dedicated creative, 20 hrs a week",
        t9uFMW25v: color ? ? props.t9uFMW25v ? ? "var(--token-7d02c183-c0db-43bb-8dd0-45785f5a79d2, rgb(9, 9, 9))",
        Tx7rB89DR: icon ? ? props.Tx7rB89DR ? ? "Check",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "m_aYOKqi1"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        a4GwngYzZ,
        t9uFMW25v,
        Tx7rB89DR,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "m_aYOKqi1",
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const ref1 = React.useRef(null);
    const defaultLayoutId = React.useId();
    const componentViewport = useComponentViewport();
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-1prusa0", className, classNames),
                    "data-framer-name": "Primary",
                    layoutDependency: layoutDependency,
                    layoutId: "m_aYOKqi1",
                    ref: ref ? ? ref1,
                    style: { ...style
                    },
                    ...addPropertyOverrides({
                        GoIavZiTY: {
                            "data-framer-name": "Tertiary"
                        },
                        MVWia3KhW: {
                            "data-framer-name": "Secondary"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-nv4jz8",
                        "data-framer-name": "Icon",
                        layoutDependency: layoutDependency,
                        layoutId: "jHVwG7spN",
                        style: {
                            backgroundColor: "var(--token-dd06214b-8b75-4dc4-a16e-5f59e222aa99, rgba(255, 70, 46, 0.2))",
                            borderBottomLeftRadius: 50,
                            borderBottomRightRadius: 50,
                            borderTopLeftRadius: 50,
                            borderTopRightRadius: 50
                        },
                        variants: {
                            GoIavZiTY: {
                                backgroundColor: "var(--token-c981f347-b2a3-4ec9-9f1d-c8a78bfbcc0b, rgb(249, 211, 205))"
                            },
                            MVWia3KhW: {
                                backgroundColor: "var(--token-c981f347-b2a3-4ec9-9f1d-c8a78bfbcc0b, rgb(249, 211, 205))"
                            }
                        },
                        children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            children: /*#__PURE__*/ _jsx(motion.div, {
                                className: "framer-4t6uez-container",
                                layoutDependency: layoutDependency,
                                layoutId: "OR25vOI44-container",
                                children: /*#__PURE__*/ _jsx(Phosphor, {
                                    color: "var(--token-7ec95c0f-b04a-42ae-a158-91566b52197d, rgb(255, 70, 46))",
                                    height: "100%",
                                    iconSearch: "House",
                                    iconSelection: Tx7rB89DR,
                                    id: "OR25vOI44",
                                    layoutId: "OR25vOI44",
                                    mirrored: false,
                                    selectByList: true,
                                    style: {
                                        height: "100%",
                                        width: "100%"
                                    },
                                    weight: "bold",
                                    width: "100%"
                                })
                            })
                        })
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-1ig73f3",
                                "data-styles-preset": "gNF6pTLez",
                                style: {
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-t9uFMW25v-M34ONsY5G))"
                                },
                                children: "One dedicated creative, 20 hrs a week"
                            })
                        }),
                        className: "framer-1tb6ydv",
                        "data-framer-name": "Text",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "eIU0e_PqX",
                        style: {
                            "--extracted-r6o4lv": "var(--variable-reference-t9uFMW25v-M34ONsY5G)",
                            "--framer-paragraph-spacing": "0px",
                            "--variable-reference-t9uFMW25v-M34ONsY5G": t9uFMW25v
                        },
                        text: a4GwngYzZ,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            GoIavZiTY: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        className: "framer-styles-preset-kd8tnc",
                                        "data-styles-preset": "Ix2IT3vgs",
                                        style: {
                                            "--framer-text-alignment": "left",
                                            "--framer-text-color": "var(--extracted-r6o4lv, var(--variable-reference-t9uFMW25v-M34ONsY5G))"
                                        },
                                        children: "One dedicated creative, 20 hrs a week"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-zI5ou.framer-812hb0, .framer-zI5ou .framer-812hb0 { display: block; }", ".framer-zI5ou.framer-1prusa0 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 323px; }", ".framer-zI5ou .framer-nv4jz8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 5px; position: relative; width: min-content; }", ".framer-zI5ou .framer-4t6uez-container { flex: none; height: 13px; position: relative; width: 13px; }", ".framer-zI5ou .framer-1tb6ydv { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-zI5ou.framer-1prusa0, .framer-zI5ou .framer-nv4jz8 { gap: 0px; } .framer-zI5ou.framer-1prusa0 > *, .framer-zI5ou .framer-nv4jz8 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-zI5ou.framer-1prusa0 > :first-child, .framer-zI5ou .framer-nv4jz8 > :first-child { margin-left: 0px; } .framer-zI5ou.framer-1prusa0 > :last-child, .framer-zI5ou .framer-nv4jz8 > :last-child { margin-right: 0px; } }", ".framer-zI5ou.framer-v-kua66c.framer-1prusa0 { width: 400px; }", ...sharedStyle.css, ...sharedStyle1.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 23
 * @framerIntrinsicWidth 322.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"MVWia3KhW":{"layout":["fixed","auto"]},"GoIavZiTY":{"layout":["fixed","auto"]}}}
 * @framerVariables {"a4GwngYzZ":"text","t9uFMW25v":"color","Tx7rB89DR":"icon"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerM34ONsY5G = withCSS(Component, css, "framer-zI5ou");
export default FramerM34ONsY5G;
FramerM34ONsY5G.displayName = "Bullet Point";
FramerM34ONsY5G.defaultProps = {
    height: 23,
    width: 322.5
};
addPropertyControls(FramerM34ONsY5G, {
    variant: {
        options: ["m_aYOKqi1", "MVWia3KhW", "GoIavZiTY"],
        optionTitles: ["Primary", "Secondary", "Tertiary"],
        title: "Variant",
        type: ControlType.Enum
    },
    a4GwngYzZ: {
        defaultValue: "One dedicated creative, 20 hrs a week",
        displayTextArea: false,
        title: "Text",
        type: ControlType.String
    },
    t9uFMW25v: {
        defaultValue: 'var(--token-7d02c183-c0db-43bb-8dd0-45785f5a79d2, rgb(9, 9, 9)) /* {"name":"Black"} */',
        title: "Color",
        type: ControlType.Color
    },
    Tx7rB89DR: PhosphorControls ? .["iconSelection"] && { ...PhosphorControls["iconSelection"],
        defaultValue: "Check",
        description: undefined,
        hidden: undefined,
        title: "Icon"
    }
});
addFonts(FramerM34ONsY5G, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...PhosphorFonts, ...getFontsFromSharedStyle(sharedStyle.fonts), ...getFontsFromSharedStyle(sharedStyle1.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerM34ONsY5G",
            "slots": [],
            "annotations": {
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]},\"MVWia3KhW\":{\"layout\":[\"fixed\",\"auto\"]},\"GoIavZiTY\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerIntrinsicWidth": "322.5",
                "framerDisplayContentsDiv": "false",
                "framerComponentViewportWidth": "true",
                "framerContractVersion": "1",
                "framerVariables": "{\"a4GwngYzZ\":\"text\",\"t9uFMW25v\":\"color\",\"Tx7rB89DR\":\"icon\"}",
                "framerIntrinsicHeight": "23",
                "framerImmutableVariables": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}