// Generated by Framer (83b8097)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-jbHvUkDcB", breakpoints: [{hash: "1ezy3gp"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-fWMCP", title: siteMetadata(params, activeLocale).title || "About", viewport: "width=1440"}
}

export const metadataVersion = 1