// Generated by Framer (4d22d44)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-Z_SjETaWJ", breakpoints: [{hash: "lu6cd9"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-O2DOj", title: siteMetadata(params, activeLocale).title || "Dark Blog", viewport: "width=1440"}
}

export const metadataVersion = 1