// Generated by Framer (3180c51)
import {
    addPropertyControls as e,
    ControlType as l,
    QueryCache as a,
    QueryEngine as r
} from "framer";
import {
    DatabaseCollection as t,
    DatabaseDictionaryIndex as m
} from "./f4zWXyw63-0.js";
import {
    getRichTextJsonResolver as o
} from "./f4zWXyw63-1.js";
let c = {
        aUomkqosW: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        bS9bpaIJn: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        CoDHlR0o5: {
            isNullable: !0,
            type: l.String
        },
        createdAt: {
            isNullable: !0,
            type: l.Date
        },
        DPqwMCprP: {
            isNullable: !0,
            type: l.String
        },
        Hpd1YW9Ey: {
            isNullable: !0,
            type: l.RichText
        },
        id: {
            isNullable: !1,
            type: l.String
        },
        IV4raZ6n2: {
            isNullable: !0,
            type: l.String
        },
        lsyaZoIpb: {
            isNullable: !0,
            type: l.Enum
        },
        MMp2v4Dri: {
            isNullable: !0,
            type: l.String
        },
        nextItemId: {
            isNullable: !0,
            type: l.String
        },
        oP7KE4iB_: {
            isNullable: !0,
            type: l.RichText
        },
        pGJYN4VEi: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        previousItemId: {
            isNullable: !0,
            type: l.String
        },
        RHVIrPLqR: {
            isNullable: !0,
            type: l.RichText
        },
        Rldl6xTYa: {
            isNullable: !0,
            type: l.RichText
        },
        rTVbj0tcf: {
            isNullable: !0,
            type: l.String
        },
        s6xPIHQ0D: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        SW_x8n3L6: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        Sw0U3zTaq: {
            isNullable: !0,
            type: l.String
        },
        SxNJq5Ync: {
            isNullable: !0,
            type: l.String
        },
        sySWngSdR: {
            isNullable: !0,
            type: l.ResponsiveImage
        },
        t152W_gsM: {
            isNullable: !0,
            type: l.RichText
        },
        uBdH78VVy: {
            isNullable: !0,
            type: l.RichText
        },
        updatedAt: {
            isNullable: !0,
            type: l.Date
        },
        uvVsKRaeN: {
            isNullable: !0,
            type: l.Link
        },
        vLhDQ2NRo: {
            isNullable: !0,
            type: l.String
        },
        W5hJRXXs_: {
            isNullable: !0,
            type: l.RichText
        },
        WA3l_h9KF: {
            isNullable: !0,
            type: l.RichText
        },
        WQGFomo23: {
            isNullable: !0,
            type: l.RichText
        },
        XVCqHbiqu: {
            isNullable: !0,
            type: l.String
        },
        xyo5kS8_c: {
            isNullable: !0,
            type: l.String
        },
        yOB0ZLHpD: {
            isNullable: !0,
            type: l.ResponsiveImage
        }
    },
    n = ["id"],
    i = {
        type: 1
    },
    s = ["previousItemId"],
    f = ["nextItemId"],
    u = ["id", "rTVbj0tcf"],
    d = ["rTVbj0tcf", "id"],
    p = ["rTVbj0tcf"],
    w = {
        type: 0
    },
    y = ["s6xPIHQ0D"],
    h = ["sySWngSdR"],
    U = ["lsyaZoIpb"],
    R = ["xyo5kS8_c"],
    g = ["SxNJq5Ync"],
    S = ["RHVIrPLqR"],
    x = ["uvVsKRaeN"],
    N = ["MMp2v4Dri"],
    W = ["Sw0U3zTaq"],
    L = ["vLhDQ2NRo"],
    X = ["uBdH78VVy"],
    z = ["CoDHlR0o5"],
    b = ["W5hJRXXs_"],
    I = ["SW_x8n3L6"],
    V = ["XVCqHbiqu"],
    E = ["oP7KE4iB_"],
    T = ["t152W_gsM"],
    D = ["yOB0ZLHpD"],
    v = ["aUomkqosW"],
    H = ["DPqwMCprP"],
    q = ["WA3l_h9KF"],
    _ = ["Hpd1YW9Ey"],
    B = ["pGJYN4VEi"],
    P = ["IV4raZ6n2"],
    Y = ["WQGFomo23"],
    k = ["Rldl6xTYa"],
    C = ["bS9bpaIJn"],
    j = [],
    A = e => {
        let l = j[e];
        if (l) return l().then(e => e.default);
    },
    J = {},
    M = o(J),
    Z = new r,
    Q = new a(Z),
    F = {
        collectionByLocaleId: {
            default: new t({
                chunks: [new URL("./f4zWXyw63-chunk-default-0.framercms",
                    import.meta.url).href.replace("/modules/", "/cms/")],
                id: "09649cd9-b70f-426a-8665-8ab5d485a8f9default",
                indexes: [new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: n,
                    range: {
                        from: 0,
                        to: 97
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: s,
                    range: {
                        from: 97,
                        to: 193
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: f,
                    range: {
                        from: 193,
                        to: 285
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: u,
                    range: {
                        from: 285,
                        to: 446
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: d,
                    range: {
                        from: 446,
                        to: 607
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: p,
                    range: {
                        from: 607,
                        to: 720
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: y,
                    range: {
                        from: 720,
                        to: 1881
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: h,
                    range: {
                        from: 1881,
                        to: 3258
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: U,
                    range: {
                        from: 3258,
                        to: 3362
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: R,
                    range: {
                        from: 3362,
                        to: 3451
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: g,
                    range: {
                        from: 3451,
                        to: 3616
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: S,
                    range: {
                        from: 3616,
                        to: 4532
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: x,
                    range: {
                        from: 4532,
                        to: 4734
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: N,
                    range: {
                        from: 4734,
                        to: 4839
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: W,
                    range: {
                        from: 4839,
                        to: 4943
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: L,
                    range: {
                        from: 4943,
                        to: 5047
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: X,
                    range: {
                        from: 5047,
                        to: 6086
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: z,
                    range: {
                        from: 6086,
                        to: 6283
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: b,
                    range: {
                        from: 6283,
                        to: 7185
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: I,
                    range: {
                        from: 7185,
                        to: 8744
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: V,
                    range: {
                        from: 8744,
                        to: 8842
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: E,
                    range: {
                        from: 8842,
                        to: 9621
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: T,
                    range: {
                        from: 9621,
                        to: 12392
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: D,
                    range: {
                        from: 12392,
                        to: 13489
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: v,
                    range: {
                        from: 13489,
                        to: 14713
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: H,
                    range: {
                        from: 14713,
                        to: 14814
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: q,
                    range: {
                        from: 14814,
                        to: 15364
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: _,
                    range: {
                        from: 15364,
                        to: 17475
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: B,
                    range: {
                        from: 17475,
                        to: 18828
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: P,
                    range: {
                        from: 18828,
                        to: 18926
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: Y,
                    range: {
                        from: 18926,
                        to: 19454
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: k,
                    range: {
                        from: 19454,
                        to: 21803
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: C,
                    range: {
                        from: 21803,
                        to: 23243
                    },
                    url: new URL("./f4zWXyw63-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                })],
                resolveRichText: M,
                resolveVectorSetItem: A,
                schema: c
            }),
            E65nUUcaa: new t({
                chunks: [new URL("./f4zWXyw63-chunk-E65nUUcaa-0.framercms",
                    import.meta.url).href.replace("/modules/", "/cms/")],
                id: "09649cd9-b70f-426a-8665-8ab5d485a8f9E65nUUcaa",
                indexes: [new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: n,
                    range: {
                        from: 0,
                        to: 97
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: s,
                    range: {
                        from: 97,
                        to: 193
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: f,
                    range: {
                        from: 193,
                        to: 285
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: u,
                    range: {
                        from: 285,
                        to: 446
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: i,
                    collectionSchema: c,
                    fieldNames: d,
                    range: {
                        from: 446,
                        to: 607
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: p,
                    range: {
                        from: 607,
                        to: 720
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: y,
                    range: {
                        from: 720,
                        to: 1881
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: h,
                    range: {
                        from: 1881,
                        to: 3258
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: U,
                    range: {
                        from: 3258,
                        to: 3362
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: R,
                    range: {
                        from: 3362,
                        to: 3451
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: g,
                    range: {
                        from: 3451,
                        to: 3616
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: S,
                    range: {
                        from: 3616,
                        to: 4532
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: x,
                    range: {
                        from: 4532,
                        to: 4734
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: N,
                    range: {
                        from: 4734,
                        to: 4839
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: W,
                    range: {
                        from: 4839,
                        to: 4945
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: L,
                    range: {
                        from: 4945,
                        to: 5058
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: X,
                    range: {
                        from: 5058,
                        to: 6097
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: z,
                    range: {
                        from: 6097,
                        to: 6299
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: b,
                    range: {
                        from: 6299,
                        to: 7201
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: I,
                    range: {
                        from: 7201,
                        to: 8760
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: V,
                    range: {
                        from: 8760,
                        to: 8861
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: E,
                    range: {
                        from: 8861,
                        to: 9640
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: T,
                    range: {
                        from: 9640,
                        to: 12411
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: D,
                    range: {
                        from: 12411,
                        to: 13508
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: v,
                    range: {
                        from: 13508,
                        to: 14732
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: H,
                    range: {
                        from: 14732,
                        to: 14836
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: q,
                    range: {
                        from: 14836,
                        to: 15386
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: _,
                    range: {
                        from: 15386,
                        to: 17497
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: B,
                    range: {
                        from: 17497,
                        to: 18850
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: P,
                    range: {
                        from: 18850,
                        to: 18954
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: Y,
                    range: {
                        from: 18954,
                        to: 19482
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: k,
                    range: {
                        from: 19482,
                        to: 21831
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new m({
                    collation: w,
                    collectionSchema: c,
                    fieldNames: C,
                    range: {
                        from: 21831,
                        to: 23271
                    },
                    url: new URL("./f4zWXyw63-indexes-E65nUUcaa-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                })],
                resolveRichText: M,
                resolveVectorSetItem: A,
                schema: c
            })
        },
        displayName: "Work Detail",
        id: "09649cd9-b70f-426a-8665-8ab5d485a8f9"
    };
export default F;
e(F, {
    rTVbj0tcf: {
        title: "Slug",
        type: l.String
    },
    s6xPIHQ0D: {
        title: "Preview Image",
        type: l.ResponsiveImage
    },
    sySWngSdR: {
        title: "Cover Image",
        type: l.ResponsiveImage
    },
    lsyaZoIpb: {
        defaultValue: "RvDpnmyAY",
        options: ["RvDpnmyAY", "WjDpUdU3H", "FI_wjoueO", "Taf5zcoQt"],
        optionTitles: ["Dot 1", "Dot 2", "Dot 3", "Dot 4"],
        title: "Option",
        type: l.Enum
    },
    xyo5kS8_c: {
        defaultValue: "",
        title: "Year",
        type: l.String
    },
    SxNJq5Ync: {
        defaultValue: "",
        title: "Title",
        type: l.String
    },
    RHVIrPLqR: {
        defaultValue: "",
        title: "Body Text",
        type: l.RichText
    },
    uvVsKRaeN: {
        title: "Site Link",
        type: l.Link
    },
    MMp2v4Dri: {
        defaultValue: "",
        title: "Tag 1",
        type: l.String
    },
    Sw0U3zTaq: {
        defaultValue: "",
        title: "Tag 2",
        type: l.String
    },
    vLhDQ2NRo: {
        defaultValue: "",
        title: "Subtitle 1",
        type: l.String
    },
    uBdH78VVy: {
        defaultValue: "",
        title: "Description",
        type: l.RichText
    },
    CoDHlR0o5: {
        defaultValue: "",
        title: "Heading",
        type: l.String
    },
    W5hJRXXs_: {
        defaultValue: "",
        title: "Body Text",
        type: l.RichText
    },
    SW_x8n3L6: {
        title: "Image 1",
        type: l.ResponsiveImage
    },
    XVCqHbiqu: {
        defaultValue: "",
        title: "Subtitle 2",
        type: l.String
    },
    oP7KE4iB_: {
        defaultValue: "",
        title: "Description",
        type: l.RichText
    },
    t152W_gsM: {
        defaultValue: "",
        title: "Body Text",
        type: l.RichText
    },
    yOB0ZLHpD: {
        title: "Image 2",
        type: l.ResponsiveImage
    },
    aUomkqosW: {
        title: "Image 3",
        type: l.ResponsiveImage
    },
    DPqwMCprP: {
        defaultValue: "",
        title: "Subtitle 3",
        type: l.String
    },
    WA3l_h9KF: {
        defaultValue: "",
        title: "Description",
        type: l.RichText
    },
    Hpd1YW9Ey: {
        defaultValue: "",
        title: "Body Text",
        type: l.RichText
    },
    pGJYN4VEi: {
        title: "Image 4",
        type: l.ResponsiveImage
    },
    IV4raZ6n2: {
        defaultValue: "",
        title: "Subtitle 4",
        type: l.String
    },
    WQGFomo23: {
        defaultValue: "",
        title: "Description",
        type: l.RichText
    },
    Rldl6xTYa: {
        defaultValue: "",
        title: "Body Text ",
        type: l.RichText
    },
    bS9bpaIJn: {
        title: "Image 5",
        type: l.ResponsiveImage
    },
    createdAt: {
        title: "Created",
        type: l.Date
    },
    updatedAt: {
        title: "Updated",
        type: l.Date
    },
    previousItemId: {
        dataIdentifier: "local-module:collection/f4zWXyw63:default",
        title: "Previous",
        type: l.CollectionReference
    },
    nextItemId: {
        dataIdentifier: "local-module:collection/f4zWXyw63:default",
        title: "Next",
        type: l.CollectionReference
    }
});
export const lsyaZoIpbToDisplayName = (e, l) => {
    switch (l ? .fallback, e) {
        case "RvDpnmyAY":
            return "Dot 1";
        case "WjDpUdU3H":
            return "Dot 2";
        case "FI_wjoueO":
            return "Dot 3";
        case "Taf5zcoQt":
            return "Dot 4";
        default:
            return "";
    }
};
export const enumToDisplayNameFunctions = {
    lsyaZoIpb: lsyaZoIpbToDisplayName
};
export const utils = {
    async getSlugByRecordId(e, l) {
        let [a] = await Q.get({
            from: {
                data: F,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "rTVbj0tcf",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "id",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l).readAsync();
        return a ? .rTVbj0tcf;
    },
    async getRecordIdBySlug(e, l) {
        let [a] = await Q.get({
            from: {
                data: F,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "id",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "rTVbj0tcf",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, l).readAsync();
        return a ? .id;
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "lsyaZoIpbToDisplayName": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "data",
            "name": "data",
            "annotations": {
                "framerCollectionUtils": "1",
                "framerContractVersion": "1",
                "framerEnumToDisplayNameUtils": "2",
                "framerData": "",
                "framerRecordIdKey": "id",
                "framerSlug": "rTVbj0tcf",
                "framerCollectionId": "f4zWXyw63",
                "framerColorSyntax": "false",
                "framerAutoSizeImages": "true"
            }
        },
        "enumToDisplayNameFunctions": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "utils": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}