// Generated by Framer (88cdfe9)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "f078js", mediaQuery: "(min-width: 1440px)"}, {hash: "mbo5u7", mediaQuery: "(min-width: 1200px) and (max-width: 1439.98px)"}, {hash: "k2m4tq", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "lrj0e6", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {MjR7vExHy: "top"}, robots: "max-image-preview:large", serializationId: "framer-WTxek", title: siteMetadata(params, activeLocale).title || "Work", viewport: "width=device-width"}
}

export const metadataVersion = 1