// Generated by Framer (c2a8602)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    Link,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle1 from "https://framerusercontent.com/modules/eWPb3aiH3Ux2vK9mD1Gs/ggFFyfN3NNEoT261fOn4/P4zHsBs8I.js";
import * as sharedStyle from "https://framerusercontent.com/modules/6d3QfczthDDHk0YK16oE/NkWCiYI14zBqmDa1RnJH/XqthePguL.js";
const enabledGestures = {
    AMtCPBu0q: {
        hover: true
    },
    lbZ94OMpJ: {
        hover: true
    }
};
const cycleOrder = ["AMtCPBu0q", "lbZ94OMpJ", "InDPFS4B8"];
const serializationHash = "framer-QoBtf";
const variantClassNames = {
    AMtCPBu0q: "framer-v-ig0ue6",
    InDPFS4B8: "framer-v-jnurkf",
    lbZ94OMpJ: "framer-v-1qmhkpf"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .6,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Not Active": "lbZ94OMpJ",
    Active: "AMtCPBu0q",
    Mobile: "InDPFS4B8"
};
const getProps = ({
    height,
    id,
    link,
    number,
    title,
    width,
    ...props
}) => {
    return { ...props,
        c95R5LzHi: number ? ? props.c95R5LzHi ? ? "01",
        DvNNqUHKC: link ? ? props.DvNNqUHKC,
        IKHeLSiEg: title ? ? props.IKHeLSiEg ? ? "Domov",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "AMtCPBu0q"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        IKHeLSiEg,
        c95R5LzHi,
        DvNNqUHKC,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "AMtCPBu0q",
        enabledGestures,
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: DvNNqUHKC,
                    motionChild: true,
                    nodeId: "AMtCPBu0q",
                    scopeId: "wZLlMfqsZ",
                    children: /*#__PURE__*/ _jsxs(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(scopingClassNames,"framer-ig0ue6",className,classNames)} framer-wy6z75`,
                        "data-framer-name": "Active",
                        layoutDependency: layoutDependency,
                        layoutId: "AMtCPBu0q",
                        ref: refBinding,
                        style: {
                            opacity: 1,
                            ...style
                        },
                        variants: {
                            "AMtCPBu0q-hover": {
                                opacity: 1
                            },
                            "lbZ94OMpJ-hover": {
                                opacity: 1
                            },
                            InDPFS4B8: {
                                opacity: 1
                            },
                            lbZ94OMpJ: {
                                opacity: .5
                            }
                        },
                        ...addPropertyOverrides({
                            "AMtCPBu0q-hover": {
                                "data-framer-name": undefined
                            },
                            "lbZ94OMpJ-hover": {
                                "data-framer-name": undefined
                            },
                            InDPFS4B8: {
                                "data-framer-name": "Mobile"
                            },
                            lbZ94OMpJ: {
                                "data-framer-name": "Not Active"
                            }
                        }, baseVariant, gestureVariant),
                        children: [ /*#__PURE__*/ _jsxs(motion.div, {
                            className: "framer-dkkg87",
                            "data-framer-name": "Text",
                            layoutDependency: layoutDependency,
                            layoutId: "RBUUXT0jF",
                            children: [ /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        className: "framer-styles-preset-wxaxcv",
                                        "data-styles-preset": "XqthePguL",
                                        children: "Home"
                                    })
                                }),
                                className: "framer-1xn2lzr",
                                "data-framer-name": "Text 1",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "f5tOWSfp5",
                                style: {
                                    "--framer-link-text-color": "rgb(0, 153, 255)",
                                    "--framer-link-text-decoration": "underline"
                                },
                                text: IKHeLSiEg,
                                verticalAlignment: "top",
                                withExternalLayout: true
                            }), /*#__PURE__*/ _jsx(RichText, {
                                __fromCanvasComponent: true,
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        className: "framer-styles-preset-wxaxcv",
                                        "data-styles-preset": "XqthePguL",
                                        children: "Home"
                                    })
                                }),
                                className: "framer-17j7mkn",
                                "data-framer-name": "Text 2",
                                fonts: ["Inter"],
                                layoutDependency: layoutDependency,
                                layoutId: "dGQZtUSji",
                                style: {
                                    "--framer-link-text-color": "rgb(0, 153, 255)",
                                    "--framer-link-text-decoration": "underline"
                                },
                                text: IKHeLSiEg,
                                verticalAlignment: "top",
                                withExternalLayout: true
                            })]
                        }), /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    className: "framer-styles-preset-165katf",
                                    "data-styles-preset": "P4zHsBs8I",
                                    children: "01"
                                })
                            }),
                            className: "framer-bmdrp8",
                            "data-framer-name": "Indicator Text",
                            fonts: ["Inter"],
                            layoutDependency: layoutDependency,
                            layoutId: "J5CxfUxDZ",
                            style: {
                                "--framer-link-text-color": "rgb(0, 153, 255)",
                                "--framer-link-text-decoration": "underline"
                            },
                            text: c95R5LzHi,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })]
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-QoBtf.framer-wy6z75, .framer-QoBtf .framer-wy6z75 { display: block; }", ".framer-QoBtf.framer-ig0ue6 { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 2px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: min-content; }", ".framer-QoBtf .framer-dkkg87 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: 22px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }", ".framer-QoBtf .framer-1xn2lzr, .framer-QoBtf .framer-17j7mkn, .framer-QoBtf .framer-bmdrp8 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-QoBtf.framer-v-jnurkf.framer-ig0ue6 { cursor: unset; }", ".framer-QoBtf.framer-v-ig0ue6.hover .framer-dkkg87, .framer-QoBtf.framer-v-1qmhkpf.hover .framer-dkkg87 { justify-content: flex-end; }", ...sharedStyle.css, ...sharedStyle1.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 22
 * @framerIntrinsicWidth 70
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"lbZ94OMpJ":{"layout":["auto","auto"]},"InDPFS4B8":{"layout":["auto","auto"]},"KlAUdDC27":{"layout":["auto","auto"]},"yzsKRlStJ":{"layout":["auto","auto"]}}}
 * @framerVariables {"IKHeLSiEg":"title","c95R5LzHi":"number","DvNNqUHKC":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerwZLlMfqsZ = withCSS(Component, css, "framer-QoBtf");
export default FramerwZLlMfqsZ;
FramerwZLlMfqsZ.displayName = "Menu Link";
FramerwZLlMfqsZ.defaultProps = {
    height: 22,
    width: 70
};
addPropertyControls(FramerwZLlMfqsZ, {
    variant: {
        options: ["AMtCPBu0q", "lbZ94OMpJ", "InDPFS4B8"],
        optionTitles: ["Active", "Not Active", "Mobile"],
        title: "Variant",
        type: ControlType.Enum
    },
    IKHeLSiEg: {
        defaultValue: "Domov",
        description: "",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    c95R5LzHi: {
        defaultValue: "01",
        displayTextArea: false,
        title: "Number",
        type: ControlType.String
    },
    DvNNqUHKC: {
        title: "Link",
        type: ControlType.Link
    }
});
addFonts(FramerwZLlMfqsZ, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts), ...getFontsFromSharedStyle(sharedStyle1.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerwZLlMfqsZ",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerVariables": "{\"IKHeLSiEg\":\"title\",\"c95R5LzHi\":\"number\",\"DvNNqUHKC\":\"link\"}",
                "framerIntrinsicWidth": "70",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"lbZ94OMpJ\":{\"layout\":[\"auto\",\"auto\"]},\"InDPFS4B8\":{\"layout\":[\"auto\",\"auto\"]},\"KlAUdDC27\":{\"layout\":[\"auto\",\"auto\"]},\"yzsKRlStJ\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerIntrinsicHeight": "22",
                "framerColorSyntax": "true",
                "framerImmutableVariables": "true",
                "framerComponentViewportWidth": "true",
                "framerDisplayContentsDiv": "false",
                "framerAutoSizeImages": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./wZLlMfqsZ.map