// Generated by Framer (88cdfe9)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "72rtr7", mediaQuery: "(min-width: 1440px)"}, {hash: "1tfs4jz", mediaQuery: "(min-width: 1200px) and (max-width: 1439.98px)"}, {hash: "1xnmc73", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "kgxcmu", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {F_2LHkNBM: "image-3", nac4JIqLJ: "top", OBr5SGreb: "image-1", VEs2GNkaw: "image-2"}, robots: "max-image-preview:large", serializationId: "framer-Kjbsb", title: siteMetadata(params, activeLocale).title || "Home", viewport: "width=device-width"}
}

export const metadataVersion = 1