// Generated by Framer (83b8097)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-GiFE_wQL3", breakpoints: [{hash: "zyilbi"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-6wpwy", title: siteMetadata(params, activeLocale).title || "Dark Home", viewport: "width=1440"}
}

export const metadataVersion = 1