// Generated by Framer (2fef4c5)

import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const aj5Onj2wB = params?.aj5Onj2wB
return {breakpoints: [{hash: "78i2bz", mediaQuery: "(min-width: 1440px)"}, {hash: "116l5k2", mediaQuery: "(min-width: 1200px) and (max-width: 1439px)"}, {hash: "zxfi8a", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "z7tuif", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {Ip7Il3wUv: "top"}, robots: "max-image-preview:large", serializationId: "framer-WB3HJ", title: `${aj5Onj2wB !== undefined ? toString(aj5Onj2wB) : "{{aj5Onj2wB}}"} - Viper - Portfolio`, viewport: "width=device-width"}
}

export const metadataVersion = 1