// Generated by Framer (ae47b7e)
import {
    fontStore
} from "framer";
fontStore.loadFonts([]);
export const fonts = [{
    explicitInter: true,
    fonts: []
}];
export const css = ['.framer-cXyWI .framer-styles-preset-11psyw8:not(.rich-text-wrapper), .framer-cXyWI .framer-styles-preset-11psyw8.rich-text-wrapper a { --framer-link-current-text-color: var(--token-f79d02c7-1774-42e8-8ffe-88585b6d572d, #1e1e1e) /* {"name":"Dark Grey"} */; --framer-link-current-text-decoration: underline; --framer-link-hover-text-color: var(--token-f79d02c7-1774-42e8-8ffe-88585b6d572d, #1e1e1e); --framer-link-hover-text-decoration: underline; --framer-link-text-color: var(--token-f79d02c7-1774-42e8-8ffe-88585b6d572d, #1e1e1e); --framer-link-text-decoration: underline; transition: color 0.4s cubic-bezier(0.44, 0, 0.56, 1) 0s; }'];
export const className = "framer-cXyWI";
export const __FramerMetadata__ = {
    "exports": {
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}