// Generated by Framer (88cdfe9)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "zy3jd0", mediaQuery: "(min-width: 1440px)"}, {hash: "1la0ucb", mediaQuery: "(min-width: 1200px) and (max-width: 1439.98px)"}, {hash: "1p8zj3s", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "1hj2otr", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {xWMThVlxb: "top"}, robots: "max-image-preview:large", serializationId: "framer-1jB9L", title: siteMetadata(params, activeLocale).title || "Contact", viewport: "width=device-width"}
}

export const metadataVersion = 1